import { Album } from "./schema"

export const data = [
  {
    artist: 'Tabby MacRierie',
    title: 'Children of the Damned',
    img: 'http://dummyimage.com/190x100.png/dddddd/000000',
    producer: 'Mills, Pouros and Gutkowski',
    format: 'DVD',
    releaseDate: '10/07/1957',
    price: 151,
    description:
      'maecenas tristique est et tempus semper est quam pharetra magna ac consequat',
    availability: 'Low Stock',
  },
  {
    artist: 'Javier Kilgannon',
    title: 'Ong-Bak 2: The Beginning (Ong Bak 2)',
    img: 'http://dummyimage.com/200x100.png/ff4444/ffffff',
    producer: 'Lebsack-Rohan',
    format: 'CD',
    releaseDate: '16/04/2015',
    price: 43,
    description:
      'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at',
    availability: 'In Stock',
  },
  {
    artist: 'Angel Bentham3',
    title: 'Roadracers',
    img: 'http://dummyimage.com/159x100.png/5fa2dd/ffffff',
    producer: 'Heathcote, Hodkiewicz and Kutch',
    format: '2LP',
    releaseDate: '27/11/1949',
    price: 105,
    description:
      'at nunc commodo placerat praesent blandit nam nulla integer pede',
    availability: 'In Stock',
  },
  {
    artist: 'Madelyn Robken',
    title: 'North and South, Book I',
    img: 'http://dummyimage.com/135x100.png/5fa2dd/ffffff',
    producer: 'Collier, Bednar and Abernathy',
    format: 'DVD',
    releaseDate: '29/10/2004',
    price: 77,
    description:
      'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis',
    availability: 'In Stock',
  },
  {
    artist: 'Arliene Beckers',
    title: 'Feast of All Saints',
    img: 'http://dummyimage.com/165x100.png/ff4444/ffffff',
    producer: 'Cummings-Rosenbaum',
    format: 'DVD',
    releaseDate: '28/12/1993',
    price: 137,
    description:
      'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut',
    availability: 'In Stock',
  },
  {
    artist: 'Sunny Kenforth',
    title: 'The Periwig-Maker',
    img: 'http://dummyimage.com/201x100.png/cc0000/ffffff',
    producer: 'Mills, Halvorson and Orn',
    format: 'DVD',
    releaseDate: '01/05/2000',
    price: 194,
    description:
      'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue',
    availability: 'In Stock',
  },
  {
    artist: 'Marwin Ivery',
    title:
      'Presentation, or Charlotte and Her Steak (Présentation ou Charlotte et son steak)',
    img: 'http://dummyimage.com/176x100.png/ff4444/ffffff',
    producer: 'Monahan, Corkery and Howe',
    format: 'CD',
    releaseDate: '01/07/1990',
    price: 182,
    description:
      'erat tortor sollicitudin mi sit amet lobortis sapien sapien non',
    availability: 'Out of Stock',
  },
  {
    artist: 'Andreana Brannon',
    title: 'Where Are My Children?',
    img: 'http://dummyimage.com/222x100.png/5fa2dd/ffffff',
    producer: 'Mayer-Barrows',
    format: 'LP',
    releaseDate: '12/07/1949',
    price: 174,
    description:
      'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam',
    availability: 'Out of Stock',
  },
  {
    artist: 'Gilburt Cutmere',
    title: 'My Name Is Nobody (Il Mio nome è Nessuno)',
    img: 'http://dummyimage.com/142x100.png/dddddd/000000',
    producer: 'Schultz LLC',
    format: 'LP',
    releaseDate: '17/05/1968',
    price: 64,
    description:
      'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo',
    availability: 'Out of Stock',
  },
  {
    artist: 'Gonzalo Gorick',
    title: "Grandma's Boy",
    img: 'http://dummyimage.com/213x100.png/ff4444/ffffff',
    producer: "O'Reilly-Moore",
    format: 'CD',
    releaseDate: '21/11/1943',
    price: 112,
    description:
      'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante',
    availability: 'Low Stock',
  },
  {
    artist: 'Mortie Hovard',
    title: 'Baby Face',
    img: 'http://dummyimage.com/127x100.png/dddddd/000000',
    producer: 'Witting-Conn',
    format: '2LP',
    releaseDate: '08/01/2011',
    price: 131,
    description:
      'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in',
    availability: 'Out of Stock',
  },
  {
    artist: 'Kirby Harbisher',
    title: 'Hit by Lightning',
    img: 'http://dummyimage.com/238x100.png/ff4444/ffffff',
    producer: 'Macejkovic Group',
    format: 'CD',
    releaseDate: '01/06/2015',
    price: 48,
    description: 'non quam nec dui luctus rutrum nulla tellus in sagittis',
    availability: 'Low Stock',
  },
  {
    artist: 'Burl Ambrois',
    title: "Man's Castle",
    img: 'http://dummyimage.com/224x100.png/5fa2dd/ffffff',
    producer: 'Price, Daniel and Goodwin',
    format: 'DVD',
    releaseDate: '17/11/1954',
    price: 162,
    description:
      'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate',
    availability: 'Low Stock',
  },
  {
    artist: 'Dotty Mulqueen',
    title: 'Kid, The',
    img: 'http://dummyimage.com/140x100.png/cc0000/ffffff',
    producer: 'Zboncak LLC',
    format: 'LP',
    releaseDate: '28/07/2019',
    price: 118,
    description:
      'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque',
    availability: 'In Stock',
  },
  {
    artist: 'Darda Slinger',
    title: '29th Street',
    img: 'http://dummyimage.com/243x100.png/cc0000/ffffff',
    producer: 'Wilderman-Nader',
    format: '2LP',
    releaseDate: '01/05/1947',
    price: 176,
    description:
      'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum',
    availability: 'Low Stock',
  },
  {
    artist: 'Sydel Zack',
    title: 'Living Room of the Nation, The (Kansakunnan olohuone)',
    img: 'http://dummyimage.com/201x100.png/5fa2dd/ffffff',
    producer: 'Gleason LLC',
    format: 'LP',
    releaseDate: '03/10/1989',
    price: 181,
    description:
      'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum',
    availability: 'In Stock',
  },
  {
    artist: 'Cordula Litterick',
    title: 'Ivul',
    img: 'http://dummyimage.com/175x100.png/dddddd/000000',
    producer: 'Jacobi, Altenwerth and Lind',
    format: 'CD',
    releaseDate: '13/07/1996',
    price: 81,
    description:
      'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis',
    availability: 'Low Stock',
  },
  {
    artist: 'Helenka Spicer',
    title: 'Creature',
    img: 'http://dummyimage.com/197x100.png/cc0000/ffffff',
    producer: 'Thompson LLC',
    format: '2LP',
    releaseDate: '28/04/1967',
    price: 161,
    description:
      'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer',
    availability: 'In Stock',
  },
  {
    artist: 'Trevor Gibbard',
    title: 'Meat Love',
    img: 'http://dummyimage.com/216x100.png/cc0000/ffffff',
    producer: 'Erdman Inc',
    format: 'LP',
    releaseDate: '17/10/1962',
    price: 138,
    description:
      'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede',
    availability: 'In Stock',
  },
  {
    artist: 'Fitzgerald Minichi',
    title: 'April Love',
    img: 'http://dummyimage.com/155x100.png/ff4444/ffffff',
    producer: 'Rath, Hansen and Wunsch',
    format: '2LP',
    releaseDate: '08/07/1948',
    price: 99,
    description:
      'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer',
    availability: 'Low Stock',
  },
  {
    artist: 'Launce Debling',
    title: 'Fans',
    img: 'http://dummyimage.com/222x100.png/5fa2dd/ffffff',
    producer: 'Kub Inc',
    format: 'LP',
    releaseDate: '27/04/1959',
    price: 161,
    description:
      'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae',
    availability: 'Low Stock',
  },
  {
    artist: 'Bryant Newbury',
    title: 'Rampo (a.k.a. The Mystery of Rampo)',
    img: 'http://dummyimage.com/152x100.png/cc0000/ffffff',
    producer: 'Wolff, Satterfield and West',
    format: 'LP',
    releaseDate: '25/06/1989',
    price: 59,
    description:
      'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at',
    availability: 'Out of Stock',
  },
  {
    artist: 'Brander Doram',
    title: '30 Minutes or Less',
    img: 'http://dummyimage.com/193x100.png/ff4444/ffffff',
    producer: 'Zemlak, Christiansen and Ullrich',
    format: '2LP',
    releaseDate: '21/06/1969',
    price: 51,
    description:
      'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue',
    availability: 'Out of Stock',
  },
  {
    artist: "D'arcy Lambrook",
    title: 'Jolene',
    img: 'http://dummyimage.com/169x100.png/5fa2dd/ffffff',
    producer: 'Bode Inc',
    format: 'LP',
    releaseDate: '13/08/2007',
    price: 128,
    description:
      'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros',
    availability: 'In Stock',
  },
  {
    artist: 'Joan Fauguel',
    title: 'Temptress, The',
    img: 'http://dummyimage.com/113x100.png/dddddd/000000',
    producer: 'Lebsack-Cremin',
    format: 'DVD',
    releaseDate: '07/06/1993',
    price: 90,
    description:
      'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci',
    availability: 'In Stock',
  },
  {
    artist: 'Benita Nelthrop',
    title: 'Samurai Spy (Ibun Sarutobi Sasuke)',
    img: 'http://dummyimage.com/219x100.png/cc0000/ffffff',
    producer: 'Grant LLC',
    format: 'DVD',
    releaseDate: '12/01/1947',
    price: 95,
    description:
      'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor',
    availability: 'Low Stock',
  },
  {
    artist: 'Merl Newbury',
    title: 'Into the Blue',
    img: 'http://dummyimage.com/224x100.png/5fa2dd/ffffff',
    producer: 'Kihn-Stehr',
    format: 'CD',
    releaseDate: '30/05/1990',
    price: 148,
    description:
      'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc',
    availability: 'Low Stock',
  },
  {
    artist: 'Enid Glazebrook',
    title: 'Breaking the Rules',
    img: 'http://dummyimage.com/177x100.png/dddddd/000000',
    producer: 'Stamm-Trantow',
    format: 'CD',
    releaseDate: '11/11/2002',
    price: 147,
    description:
      'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet',
    availability: 'Low Stock',
  },
  {
    artist: 'Biron Memmory',
    title: 'Zero 2',
    img: 'http://dummyimage.com/169x100.png/5fa2dd/ffffff',
    producer: 'Zboncak, Collins and Jacobi',
    format: 'LP',
    releaseDate: '31/05/1978',
    price: 107,
    description:
      'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla',
    availability: 'In Stock',
  },
  {
    artist: 'Isacco Tett',
    title: 'Woman Chaser, The',
    img: 'http://dummyimage.com/240x100.png/cc0000/ffffff',
    producer: 'Shanahan Inc',
    format: 'CD',
    releaseDate: '23/01/2006',
    price: 92,
    description:
      'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet',
    availability: 'Low Stock',
  },
  {
    artist: 'Aloise Sinnott',
    title: 'Pretty Woman',
    img: 'http://dummyimage.com/172x100.png/dddddd/000000',
    producer: 'Schiller-Kris',
    format: 'CD',
    releaseDate: '09/02/1999',
    price: 159,
    description:
      'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat',
    availability: 'In Stock',
  },
  {
    artist: 'Ashlan Layzell',
    title: 'Chu Chin Chow',
    img: 'http://dummyimage.com/171x100.png/ff4444/ffffff',
    producer: 'Effertz Inc',
    format: '2LP',
    releaseDate: '25/09/1967',
    price: 152,
    description:
      'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit',
    availability: 'Out of Stock',
  },
  {
    artist: 'Elsi Coo',
    title: 'Attack of the Crab Monsters',
    img: 'http://dummyimage.com/199x100.png/5fa2dd/ffffff',
    producer: 'Dietrich-Champlin',
    format: '2LP',
    releaseDate: '02/09/2006',
    price: 76,
    description:
      'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent',
    availability: 'Out of Stock',
  },
  {
    artist: 'Jennee Ford',
    title: 'Dead & Breakfast',
    img: 'http://dummyimage.com/136x100.png/5fa2dd/ffffff',
    producer: 'Wilderman Inc',
    format: 'CD',
    releaseDate: '12/01/1967',
    price: 121,
    description:
      'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue',
    availability: 'In Stock',
  },
  {
    artist: 'Chip Dommersen',
    title: 'Wind Will Carry Us, The (Bad ma ra khahad bord)',
    img: 'http://dummyimage.com/224x100.png/ff4444/ffffff',
    producer: 'Waters, Parisian and Beer',
    format: 'DVD',
    releaseDate: '31/10/1954',
    price: 144,
    description:
      'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices',
    availability: 'Out of Stock',
  },
  {
    artist: 'Toma Osmond',
    title: 'Flicker',
    img: 'http://dummyimage.com/162x100.png/5fa2dd/ffffff',
    producer: 'Greenfelder-Gutkowski',
    format: '2LP',
    releaseDate: '04/11/1944',
    price: 64,
    description:
      'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit',
    availability: 'In Stock',
  },
  {
    artist: 'Ellsworth Dimsdale',
    title: 'Fire Down Below',
    img: 'http://dummyimage.com/111x100.png/dddddd/000000',
    producer: 'Lockman-Stokes',
    format: 'CD',
    releaseDate: '14/09/1947',
    price: 179,
    description:
      'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et',
    availability: 'Low Stock',
  },
  {
    artist: 'Heath Potebury',
    title: 'Read My Lips (Sur mes lèvres)',
    img: 'http://dummyimage.com/220x100.png/ff4444/ffffff',
    producer: 'Kris, Kerluke and Wisozk',
    format: 'CD',
    releaseDate: '11/09/1979',
    price: 181,
    description:
      'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue',
    availability: 'Low Stock',
  },
  {
    artist: 'Herrick Camlin',
    title: 'Crimes of the Future',
    img: 'http://dummyimage.com/212x100.png/ff4444/ffffff',
    producer: 'Treutel-Conn',
    format: 'CD',
    releaseDate: '08/05/1966',
    price: 76,
    description:
      'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices',
    availability: 'Out of Stock',
  },
  {
    artist: 'Alvy Grant',
    title: 'Capitalism: A Love Story',
    img: 'http://dummyimage.com/146x100.png/dddddd/000000',
    producer: 'Nader-McClure',
    format: 'DVD',
    releaseDate: '20/01/1944',
    price: 190,
    description:
      'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur',
    availability: 'Out of Stock',
  },
  {
    artist: 'Gerhard Haycock',
    title: 'Black Rainbow',
    img: 'http://dummyimage.com/222x100.png/cc0000/ffffff',
    producer: 'Fisher-Klocko',
    format: '2LP',
    releaseDate: '17/04/2007',
    price: 68,
    description:
      'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna',
    availability: 'Low Stock',
  },
  {
    artist: 'Jefferey Kiernan',
    title: 'Marva Collins Story, The',
    img: 'http://dummyimage.com/199x100.png/5fa2dd/ffffff',
    producer: 'Simonis, Mosciski and Hammes',
    format: 'CD',
    releaseDate: '30/09/1978',
    price: 185,
    description:
      'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper',
    availability: 'In Stock',
  },
  {
    artist: 'Karlyn Plak',
    title: 'Big Man Japan (Dai-Nihonjin)',
    img: 'http://dummyimage.com/145x100.png/5fa2dd/ffffff',
    producer: 'Fay-Cummerata',
    format: '2LP',
    releaseDate: '19/09/1981',
    price: 76,
    description:
      'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque',
    availability: 'Low Stock',
  },
  {
    artist: 'Zachery Boner',
    title: 'Wish You Were Here',
    img: 'http://dummyimage.com/186x100.png/ff4444/ffffff',
    producer: 'Goyette Group',
    format: 'CD',
    releaseDate: '16/01/1951',
    price: 103,
    description:
      'felis ut at dolor quis odio consequat varius integer ac leo pellentesque',
    availability: 'In Stock',
  },
  {
    artist: 'Burl Walcar',
    title: 'Dead Like Me: Life After Death',
    img: 'http://dummyimage.com/116x100.png/5fa2dd/ffffff',
    producer: 'Brekke-Davis',
    format: 'LP',
    releaseDate: '30/09/1949',
    price: 112,
    description:
      'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in',
    availability: 'Out of Stock',
  },
  {
    artist: 'Anny Stevani',
    title: 'Machete',
    img: 'http://dummyimage.com/220x100.png/ff4444/ffffff',
    producer: 'Turcotte LLC',
    format: 'CD',
    releaseDate: '19/10/2020',
    price: 51,
    description:
      'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula',
    availability: 'In Stock',
  },
  {
    artist: 'Reina Ibell',
    title: 'Stardust',
    img: 'http://dummyimage.com/223x100.png/dddddd/000000',
    producer: 'Kirlin and Sons',
    format: 'CD',
    releaseDate: '27/11/1959',
    price: 161,
    description:
      'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum',
    availability: 'Low Stock',
  },
  {
    artist: 'Torin Medlicott',
    title: 'Sada',
    img: 'http://dummyimage.com/199x100.png/dddddd/000000',
    producer: 'Goodwin-Hackett',
    format: 'CD',
    releaseDate: '13/02/2008',
    price: 57,
    description:
      'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt',
    availability: 'In Stock',
  },
  {
    artist: 'Dreddy Bootyman',
    title: 'Moment of Truth, The (Il momento della verità)',
    img: 'http://dummyimage.com/245x100.png/dddddd/000000',
    producer: 'Veum LLC',
    format: '2LP',
    releaseDate: '17/09/1994',
    price: 168,
    description:
      'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros',
    availability: 'In Stock',
  },
  {
    artist: 'Darrel MacColl',
    title: 'Mallrats',
    img: 'http://dummyimage.com/151x100.png/dddddd/000000',
    producer: 'Jerde Group',
    format: '2LP',
    releaseDate: '06/08/2005',
    price: 175,
    description:
      'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae',
    availability: 'Low Stock',
  },
]
